### PR TITLE
update responsibility and add jong

### PR DESCRIPTION
**Pull request by jshinm**
addressing #603 issues

### CODE REVIEW

**Comment by jshinm** [comment]
@tathey1 @m-powell are you guys okay with the changes? Please let me know 😃

**Comment by m-powell** [comment]
@jshinm I'm fine with all changes but would make the following notes:
* "Being a Person" can be removed completely since we no longer do that meeting as a lab.
* I've been coordinating/reminding lab meeting presenters, but this is my last week in lab.  We're covered through May 12th, but it's time to replace me in that role.  I'll solicit volunteers.

**Comment by tathey1** [comment]
Do either of you think it'd be useful if we had these roles expire? Like rather than signing on indefinitely, you commit for a certain number of months, say?

**Comment by m-powell** [comment]
Some are more easily handed off than others (social organizer, lab meeting
organizer, etc. vs. AWS manager).  I think some roles can be filled by
anybody, and others need the right person.  Passing those responsibilities
along to the next "right person" is important to do, especially for the
more time-consuming stuff.  One-year terms seem appropriate, but that
requires a new volunteer and trainup process.  When possible, finding your
own replacement is the best practice to facilitate transferring whatever
knowledge is needed to not drop any balls during the changeover.

Also, @jshinm, Alice offered to take over as lab meeting organizer.

**Comment by jshinm** [comment]
@m-powell @tathey1 Thank you for your great feedback, guys! I will 1. remove the section for `being a person` 2. add Alice 3. maybe get some thoughts on commitment term (maybe have two people for each task?).

Should this be in our agreement term? Seems like great instruction 

> Some are more easily handed off than others (social organizer, lab meeting
organizer, etc. vs. AWS manager).  I think some roles can be filled by
anybody, and others need the right person.  Passing those responsibilities
along to the next "right person" is important to do, especially for the
more time-consuming stuff.  One-year terms seem appropriate, but that
requires a new volunteer and trainup process.  When possible, finding your
own replacement is the best practice to facilitate transferring whatever
knowledge is needed to not drop any balls during the changeover.

**Pull request merged**
