### PR TITLE
Add Ashwin's Profile to the Website

### PR DESCRIPTION
**Pull request by Laknath1996**

### CODE REVIEW

**Review by jshinm — APPROVED** [review]
I corrected your website address

**Comment by jshinm** [comment]
@Laknath1996 you didn't mean to make this PR into the deploy right?

**Comment by Laknath1996** [comment]
> @Laknath1996 you didn't mean to make this PR into the deploy right?

Hey @jshinm, I followed the guidelines provided by @Lawreros in the core slack channel to add my details to the neurodata.io website. There, we were asked to the PR to the yaml_conversion branch. I was thinking that the deployment was done by later by the repo-manager after checking the pushes :)

**Comment by jshinm** [comment]
@Laknath1996 oh I see, I think that's when Ross was having a major update on everyone's profile back in July. I'm not sure if we are making that a standard practice. I think now everyone's just making a PR directly into the deploy branch unless Ross believes otherwise. Thank you for being sensible on this!

**Comment by Laknath1996** [comment]
> @Laknath1996 oh I see, I think that's when Ross was having a major update on everyone's profile back in July. I'm not sure if we are making that a standard practice. I think now everyone's just making a PR directly into the deploy branch unless Ross believes otherwise. Thank you for being sensible on this!

Ohh! now it makes sense! Is there a chance to merge the yaml_conversion branch with the deploy branch? Or shall I make a new PR to deploy branch? Please let me know which way would be easy :)
UPDATE: I made a new PR to the deploy branch directly

**Pull request merged**
