### PR TITLE
update publication agreement on quote usage

### PR DESCRIPTION
**Pull request by jshinm**
update upon Jovo's request

### CODE REVIEW

**Comment by jshinm** [comment]
@tathey1 Jovo requested that we add the section for quote usage on publications. Could you please review this?

**Review by tathey1 — COMMENTED** [review]
To be honest, I don't understand this. What is the motivation behind adding this? Is there an existing barrier to having quotes in papers? Also, is this saying that we should investigate the moral lives of some scientist every time we consider referencing their work? Seems like an odd and potentially burdensome responsibility.

**Comment by jshinm** [comment]
@tathey1 I see that's a good point. My guess is that when quoting someone in the paper, all authors need to come to a collective agreement before the paper is submitted (especially the person being quoted is a politician). Unfortunately, we have recently had an issue regarding that, and I think Jovo wants to raise a point that everything that you write in the paper matters. But in my personal opinion, though, even quoting scientists should be discreet and discussed among co-authors. For instance, I would be uncomfortable if the paper I am co-authoring is quoting some brutal scientist from Unit 731.

**Comment by tathey1** [comment]
I absolutely agree that references should be made thoughtfully and that it's just a reality that references can come across as an endorsement of other things in the author's life.

However, I think the wording of this statement is a little inappropriate considering it is made in the context of a scientific laboratory. In particular:

- Quoting someone typically involves an appeal to authority i.e. using the person's reputation to support some argument. We as a lab make scientific arguments, and scientific arguments should be based on verifiable sources. The argument of `some famous person said that this method is better than that method` is inferior to more objective evidence. Thus, I am confused why we are encouraging people to use quotes in our research. Of course, if the quote is just to establish some context, rather than support some argument, then that is just a matter of writing style and I don't think it is necessary to add as a core agreement of our lab.
- Even though, as I stated earlier, quotes can be endorsements of someone's background and moral actions, I think that the vast majority of the time these things are irrelevant, and hard to judge. Of course I would not want to cite some horrible person, but in less obvious cases, who is the right judge for those things and where do you draw the line? Further, isn't the content of the quote the important part in science, not their background or moral life? Again, I think these things are important to consider, but I don't think we realistically will, or want to, be regularly evaluating the personal lives of the scientists we cite.

So, I'm still skeptical that this belongs in our agreements, but if it is really important to some of us, I would be more inclined to go for something like `Quotes can be a useful device in adding style or establishing context in scientific writing, but we acknowledge that quotes can come across as an endorsement of the personal life of the author. Therefore, quotes should be carefully considered by all authors of a paper.`

**Comment by jshinm** [comment]
@tathey1 Thank you for your response! I don't know what Jovo might say about the first bullet point, and I am not sure if that at all is Jovo's intention with the sentence he wants to add. I personally found your second bullet point nice argument for Jovo, and I personally agree that none of us are moral judges for one another.

I believe Jovo's asked me to consult you for reason, and I feel that you are not fully convinced, and I think you deserve some feedback from Jovo after taking your valuable time writing out your thoughts! I will send Jovo an email with your response (nice and respectfully packaged of course), and relay the message to you. Just fyi, I'm being careful for reason. I will get back to you soon!

**Comment by tathey1** [comment]
@jshinm Of course. Again, I'm just giving my two cents, so thanks for your patience. Always happy to discuss these things.

**Comment by jshinm** [comment]
@tathey1 I've delivered your message along with your nice suggestion. Though, Jovo emphasizes that the term only pertains to non-scientific quotes in that they are simply extraneous (trying to copy his exact wording here). Did Jovo's response resolve your concern at least little bit? If not, my suggestion is to put your suggested term immediately after Jovo's. Your thoughts, Tommy?

**Comment by tathey1** [comment]
I think that helps, but it should be incorporated in the wording of the PR, can you please add that clarification to the text @jshinm

**Comment by jshinm** [comment]
@tathey1 As requested, I've added the exact wording you've introduced in the agreement. Could you please check?

**Comment by tathey1** [comment]
@jshinm i changed the wording and approved.

**Review by tathey1 — APPROVED** [review]
looks good.

**Comment by jshinm** [comment]
@tathey1 Thank you so much for your input, Tommy!

**Pull request merged**
