### PR TITLE
Update pubs.bib

### PR DESCRIPTION
**Pull request by tliu68**

### CODE REVIEW

**Review by tathey1 — CHANGES_REQUESTED** [review]
i believe that "doi" should be changed to "arxivid" actually. i don't think arxiv issues doi's, but i may be mistaken

**Review by Lawreros — DISMISSED** [review]

**Comment by tliu68** [comment]
@Lawreros Should I change anything?

**Comment by tathey1** [comment]
@Lawreros I think doi should be changed to arxivid. I was hoping @tliu68 could do this since its in her fork.

**Review by tathey1 — APPROVED** [review]
looks good, thanks tingshan!

**Pull request merged**
