### PR TITLE
add descriptions for graspy and lol

### PR DESCRIPTION
**Pull request by j1c**

### CODE REVIEW

**Review by falkben — APPROVED** [review]

**Comment by j1c** [comment]
@falkben For LOL, and I suppose for mgc and other cross-language packages, I wanted to make a link to R github repo and Python github repo in the nav bar. Can i modify the `tool-page-nav.html` to do that (I know how. Just asking if Im allowed to do that)?

**Comment by j1c** [comment]
@bdpedigo See [here](https://deploy-preview-200--demo-neurodata.netlify.com/graspy/). Let me know what you think.

**Comment by bdpedigo** [comment]
Maybe statistical learning or statistical inference instead of the term
machine learning?

**Comment by loftusa** [comment]
> @falkben For LOL, and I suppose for mgc and other cross-language packages, I wanted to make a link to R github repo and Python github repo in the nav bar. Can i modify the `tool-page-nav.html` to do that (I know how. Just asking if Im allowed to do that)?

@j1c  It's not in `tool-page-nav.html` -- if I understand what you're asking, https://neurodata.io/tools/ is generated by `tools_detail_list.html` referencing the individual yaml files in `tools`. I think you'll want to edit `content/tools/lol.yaml`, and the other yaml files in `content/tools`

**Comment by j1c** [comment]
@loftusa Im talking about the top right links in the nav bar for specific tool page like mgc not the current tool link from neurodata.io. Given [tool-page-nav.html](https://github.com/neurodata/neurodata.io/blob/deploy/partials/tool-page-nav.html), I can only make links that are called `DOCS`, `INSTALLATION`, `EXAMPLES` and `GITHUB`. I can't create my own like `R-GITHUB` or `PYTHON-GITHUB` because this html doesn't allow you to.

image

**Comment by loftusa** [comment]
@j1c oh, I see what you're saying. Didn't see the 'I know how' at the end

**Pull request merged**
