### PR TITLE
add @jovo's agreements/about page updates

### PR DESCRIPTION
**Pull request by falkben**
formatting

### CODE REVIEW

**Review by jovo — COMMENTED** [review]
the preview says "Not Found" when i click the link, and nothing else.
doesn't seem like a good sign?

**Comment by falkben** [comment]
Fixed.  Was a netlify config error.

**Review by jovo — APPROVED** [review]

**Comment by jovo** [comment]
still hasn't generated a preview?

**Comment by falkben** [comment]
> still hasn't generated a preview?

branch protection was still referencing old netlify config.

**Pull request merged**
