### PR TITLE
DOC add open source contributions

### PR DESCRIPTION
**Pull request by asaadeldin11**
#459 Adds open source code from jovo's cv

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@asaadeldin11 `hyppo` is `MGC`, @sampan501 will change that page.

**Comment by asaadeldin11** [comment]
> @asaadeldin11 `hyppo` is `MGC`, @sampan501 will change that page.

so should I just remove mgc from the code page?

**Comment by PSSF23** [comment]
I suggest leaving `hyppo` related changes to @sampan501 .

**Review by PSSF23 — COMMENTED** [review]
Also, I think we should keep the code urls for now. Sometimes the code project spans across many papers/slides and there's no other way to link them.

**Review by PSSF23 — COMMENTED** [review]
Checked again and confirmed that the pages will still be accessible through url.

**Comment by asaadeldin11** [comment]
good to merge?

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
